// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VibraScan.Infrastructure.Data;

#nullable disable

namespace VibraScan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VibraScan.Domain.Entities.Engine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<long?>("InspectionRuleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NextInspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WorkshopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRuleId");

                    b.HasIndex("WorkshopId", "Name")
                        .IsUnique();

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.InspectionInterval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DaysCount")
                        .HasColumnType("int");

                    b.Property<long>("InspectionRuleId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetCondition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionRuleId", "TargetCondition")
                        .IsUnique();

                    b.ToTable("InspectionIntervals");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.InspectionRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InspectionRules");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.MeasurementProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("MeasurementProfiles");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.Point", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EngineId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EngineId", "Name")
                        .IsUnique();

                    b.ToTable("Points");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.VibrationMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AxisType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeasurementDomain")
                        .HasColumnType("int");

                    b.Property<long>("MeasurementProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("PointId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RawData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("Rms")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AxisType");

                    b.HasIndex("MeasurementProfileId");

                    b.HasIndex("CapturedAt", "MeasurementDomain")
                        .IsUnique();

                    b.HasIndex("PointId", "AxisType", "MeasurementProfileId", "CapturedAt");

                    b.ToTable("VibrationMeasurements");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.Workshop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.Engine", b =>
                {
                    b.HasOne("VibraScan.Domain.Entities.InspectionRule", null)
                        .WithMany()
                        .HasForeignKey("InspectionRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VibraScan.Domain.Entities.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.InspectionInterval", b =>
                {
                    b.HasOne("VibraScan.Domain.Entities.InspectionRule", null)
                        .WithMany("Intervals")
                        .HasForeignKey("InspectionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.Point", b =>
                {
                    b.HasOne("VibraScan.Domain.Entities.Engine", null)
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.VibrationMeasurement", b =>
                {
                    b.HasOne("VibraScan.Domain.Entities.MeasurementProfile", null)
                        .WithMany()
                        .HasForeignKey("MeasurementProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VibraScan.Domain.Entities.Point", null)
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VibraScan.Domain.Entities.InspectionRule", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
