<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VibraScan.Application\VibraScan.Application.csproj" />
    <ProjectReference Include="..\VibraScan.Domain\VibraScan.Domain.csproj" />
    <ProjectReference Include="..\VibraScan.Infrastructure\VibraScan.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
